### PR TITLE
Bug Fix + Minor Improvements

### PR DESCRIPTION
**Pull request by wyatt-herkamp**
So I fixed the getSongByFile. It wasn't working on my system. I also added a TabCompleter + improved the help menu.

### CODE REVIEW

**Comment by SkytAsul** [comment]
Sorry, I haven't seen this PR. The tab-completion and help things would be cool, but before contributing please make sure you're using the same format. Here you have replaced all the tabs by spaces, which makes the diff pretty unreadable.

**Comment by wyatt-herkamp** [comment]
> Sorry, I haven't seen this PR. The tab-completion and help things would be cool, but before contributing please make sure you're using the same format. Here you have replaced all the tabs by spaces, which makes the diff pretty unreadable.

This will probably require a redo due to the recent changes. Also Intellij was just trying to fix it to the Java Style Format.

**Comment by SkytAsul** [comment]
> This will probably require a redo due to the recent changes. Also Intellij was just trying to fix it to the Java Style Format.

Yup
You can close this PR and reopen one if you want to. Otherwise, I might be able to redo it easily if you want!

**Comment by wyatt-herkamp** [comment]
Ok

**Pull request closed without merging**
